version: '3.7'

services:

  postgres:
    image: postgres:11.6
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:Z
    env_file:
      - './rails_app/.env'
    ports:
      - "5432:5432"

volumes:
  postgres: